import 'package:flutter_guid/flutter_guid.dart';

import './transactions.dart';

final dummyData = [
  Transaction(
    id: Guid.newGuid,
    amount: 2000,
    transactionDateTime: DateTime.now(),
    transactionType: true,
    bankName: 'Firstbank of Nigeria',
    customerName: 'William Johnson',
    ref: DateTime.now().millisecondsSinceEpoch.toString(),
  ),
  Transaction(
    id: Guid.newGuid,
    amount: 2000,
    transactionDateTime: DateTime.now(),
    transactionType: true,
    bankName: 'Firstbank of Nigeria',
    customerName: 'William Johnson',
    ref: DateTime.now().millisecondsSinceEpoch.toString(),
  ),
  Transaction(
    id: Guid.newGuid,
    amount: 2000,
    transactionDateTime: DateTime.now(),
    transactionType: true,
    bankName: 'Firstbank of Nigeria',
    customerName: 'William Johnson',
    ref: DateTime.now().millisecondsSinceEpoch.toString(),
  ),
  Transaction(
    id: Guid.newGuid,
    amount: 2000,
    transactionDateTime: DateTime.now(),
    transactionType: true,
    bankName: 'Firstbank of Nigeria',
    customerName: 'William Johnson',
    ref: DateTime.now().millisecondsSinceEpoch.toString(),
  ),
  Transaction(
    id: Guid.newGuid,
    amount: 2000,
    transactionDateTime: DateTime.now(),
    transactionType: true,
    bankName: 'Firstbank of Nigeria',
    customerName: 'William Johnson',
    ref: DateTime.now().millisecondsSinceEpoch.toString(),
  ),
  Transaction(
    id: Guid.newGuid,
    amount: 2000,
    transactionDateTime: DateTime.now(),
    transactionType: true,
    bankName: 'Firstbank of Nigeria',
    customerName: 'William Johnson',
    ref: DateTime.now().millisecondsSinceEpoch.toString(),
  ),
  Transaction(
    id: Guid.newGuid,
    amount: 2000,
    transactionDateTime: DateTime.now(),
    transactionType: true,
    bankName: 'Firstbank of Nigeria',
    customerName: 'William Johnson',
    ref: DateTime.now().millisecondsSinceEpoch.toString(),
  ),
  Transaction(
    id: Guid.newGuid,
    amount: 2000,
    transactionDateTime: DateTime.now(),
    transactionType: true,
    bankName: 'Firstbank of Nigeria',
    customerName: 'William Johnson',
    ref: DateTime.now().millisecondsSinceEpoch.toString(),
  ),
  Transaction(
    id: Guid.newGuid,
    amount: 2000,
    transactionDateTime: DateTime.now(),
    transactionType: true,
    bankName: 'Firstbank of Nigeria',
    customerName: 'William Johnson',
    ref: DateTime.now().millisecondsSinceEpoch.toString(),
  ),
  Transaction(
    id: Guid.newGuid,
    amount: 2000,
    transactionDateTime: DateTime.now(),
    transactionType: true,
    bankName: 'Firstbank of Nigeria',
    customerName: 'William Johnson',
    ref: DateTime.now().millisecondsSinceEpoch.toString(),
  )
];
